-- AlterTable
ALTER TABLE "User" RENAME COLUMN "tokenUsage" TO "tokenUsageTotal";
ALTER TABLE "User" ADD COLUMN "tokenUsageWindow"  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "tokenLimit"        INTEGER NOT NULL DEFAULT 50000;
ALTER TABLE "User" ADD COLUMN "scrapeUsageTotal"  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "scrapeUsageWindow" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "scrapeLimit"       INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "User" ADD COLUMN "nextQuotaReset"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
